#!/bin/bash -x
activator clean
activator stage
activator preloader/clean
activator preloader/package
mkdir target/universal/stage/preloader/
cp preloader/target/scala-2.11/preloader_2.11-0.1-SNAPSHOT.jar target/universal/stage/preloader/preloader_2.11-0.1-SNAPSHOT.jar
cp preloader/target/streams/compile/dependencyClasspath/\$global/streams/export target/universal/stage/preloader/export
cp bin/preload target/universal/stage/bin/preload